<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>vn.codezx</groupId>
    <artifactId>algorithm</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>algorithm</name>
    <packaging>jar</packaging>
    <properties>
        <java.version>22</java.version>
    </properties>
    <dependencies>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>
                              vn.codezx.algorithm.advance.PrePostPlus
                            </mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
              <source>9</source>
              <target>9</target>
            </configuration>
          </plugin>
        </plugins>
    </build>


</project>
